# Generated by Django 4.0.4 on 2022-08-04 04:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_id', models.IntegerField()),
                ('annotation_0', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('annotation_1', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('annotation_2', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('annotation_3', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('workflow_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
